# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'BatchFetchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LotsOfData
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'SVProgressHUD'
  pod 'ObjectMapper'

end
